### PR TITLE
stuff

### PR DESCRIPTION
**Pull request by ParaSpider**

### CODE REVIEW

**Comment by matic0basle** [comment]
Was it just removed from rotations? When I made this it was still on

**Comment by ParaSpider** [comment]
No, it's removed

**Comment by ParaSpider** [comment]
That server hasn't updated yet, if it loads it'll crash

**Comment by matic0basle** [comment]
@ParaSpider I checked on 3 servers so you might want to do something about that then. Will merge though, thanks.

**Comment by ParaSpider** [comment]
Okay

**Pull request merged**
